language: python
python:
      - "3.6"
services:
    - postgresql
env:
    global:
        - CODECOV_TOKEN="b3c5d783-c66e-41c9-bbb1-8242f56c1f01"
addons:
    postgresql: "9.6"
    chrome: stable
install:
    - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux32.zip -P ~/
    - unzip ~/chromedriver_linux32.zip -d ~/
    - rm ~/chromedriver_linux32.zip
    - sudo mv -f ~/chromedriver /usr/local/share/
    - sudo chmod +x /usr/local/share/chromedriver
    - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
    - pip install -r requirements.txt

before_script:
    - psql -c 'create database mydb;' -U postgres
script:
    - whereis google-chrome-stable
    - whereis chromedriver
    - python manage.py collectstatic --noinput --clear
    - python manage.py test
    - coverage run manage.py test
after_success:
    - codecov