language: python
python:
      - "3.6"
services:
    - postgresql
env:
    - DJANGO=2
install:
    - pip install -r requirements.txt
addons:
    postgresql: "9.6"
before_script:
    - psql -c 'create database mydb;' -U postgres
script:
    - python manage.py collectstatic
    - python manage.py test
