language: python
python:
      - "3.6"
services:
    - postgresql
env:
    - DJANGO=2
    global:
        - CODECOV_TOKEN="b3c5d783-c66e-41c9-bbb1-8242f56c1f01"
install:
    - pip install -r requirements.txt
addons:
    postgresql: "9.6"
before_script:
    - psql -c 'create database mydb;' -U postgres
script:
    - python manage.py collectstatic --noinput --clear
    - python manage.py test
    - coverage run manage.py test
after_success:
    - codecov