# Generated by Django 2.1.2 on 2018-10-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('recipe_name', models.CharField(max_length=30)),
                ('recipe_info', models.TextField()),
                ('recipe_time', models.IntegerField(null=True)),
                ('recipe_type', models.CharField(max_length=15)),
                ('recipe_fat', models.IntegerField(null=True)),
                ('recipe_ingredient', models.TextField()),
                ('recipe_method', models.TextField()),
            ],
        ),
    ]
