# Generated by Django 2.1.1 on 2018-10-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_auto_20181025_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image_1',
            field=models.ImageField(upload_to='recipe_image/'),
        ),
    ]
