# Generated by Django 2.1.2 on 2018-10-29 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0007_auto_20181028_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_type',
            new_name='recipe_equipment',
        ),
    ]
