# Generated by Django 2.1.2 on 2018-11-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0009_auto_20181101_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_chef',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_equipment',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=100),
        ),
    ]
