# Generated by Django 2.1.2 on 2018-11-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0010_auto_20181101_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(max_length=100)),
                ('recipe_name', models.CharField(max_length=100)),
            ],
        ),
    ]
