# Generated by Django 2.1.2 on 2018-11-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0011_authoruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(max_length=100)),
                ('alis_name', models.CharField(max_length=50)),
            ],
        ),
    ]
