# Generated by Django 2.1.2 on 2018-11-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0012_useralias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useralias',
            old_name='alis_name',
            new_name='alias_name',
        ),
    ]
