# Generated by Django 2.1.2 on 2018-12-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0013_auto_20181127_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralias',
            name='alias_name',
            field=models.CharField(max_length=1000),
        ),
    ]
